### ISSUE TITLE
spring boot 2.5.0中修改了数据库相关配置，需要对应修改项目配置

### ISSUE THREAD

**Issue by gadfly3173** [TaleLin/lin-cms-spring-boot#209]
现在spring在项目启动时会自动执行schema.sql来进行数据库初始化，需要在dev和prod环境配置文件中加上相关配置：
```yaml

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    # 常规数据源配置
  sql:
    init:
      enabled: false
```
test配置则需要修改为：
```yaml
spring:
  # h2 内存数据库配置，供测试使用，其它环境勿用
  datasource:
    username: "sa"
    password: ''
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdbsa;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  sql:
    init:
      platform: h2
      continue-on-error: false
      schema-locations: classpath:/h2-test.sql
  h2:
    console:
      enabled: true
      path: /h2

```
